// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8OXiawAc1yJhQlXYMglWMeLYOjjN6nJg',
    appId: '1:314737802800:web:4fa67f7e728c551effb7f5',
    messagingSenderId: '314737802800',
    projectId: 'mykpcapp',
    authDomain: 'mykpcapp.firebaseapp.com',
    storageBucket: 'mykpcapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0fqApaMIPS-iMZR3Nge6JVTLentikDO8',
    appId: '1:314737802800:android:9c0e1745225a3ba1ffb7f5',
    messagingSenderId: '314737802800',
    projectId: 'mykpcapp',
    storageBucket: 'mykpcapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXQ21ax6IHn16I0V0e-Ere9bb0Rnfm0qU',
    appId: '1:314737802800:ios:9cfe300807dabaa6ffb7f5',
    messagingSenderId: '314737802800',
    projectId: 'mykpcapp',
    storageBucket: 'mykpcapp.appspot.com',
    iosBundleId: 'com.example.mykpcApp',
  );
}
